services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tsf\AssetBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Model/'
            - '../src/Installer.php'
            - '../src/TsfAssetBundle.php'

    Tsf\AssetBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('TsfAssetBundle')"

    Tsf\AssetBundle\EventListener\DataObjectListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd, method: onPostAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreUpdate }

    Tsf\AssetBundle\EventListener\DocumentListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.document.postAdd, method: onPostAdd }
            - { name: kernel.event_listener, event: pimcore.document.preUpdate, method: onPreUpdate }
